### ISSUE TITLE
Starter & Cabin Kits remain in active loadouts after completing a prospect

### ISSUE THREAD

**Issue by DreamingLamb** [laanp/Icarus_Mods#1]
I've been using your mod as a guide to create some custom kits for me and my friends and I've noticed that your starter and cabin kits are showing as still being on a prospect, after consuming it and returning to station.  The seed kit is unaffected.

I believe this is due to adding the following tag to the kits:
```
"Manual_Tags": {
    "GameplayTags": [
        {
             "TagName": "Item.Meta"
        }
    ]
},
```

With it being in seed packs, I don't believe this tag needs to be in the mod or it should be corrected to 
`"TagName": "Item.Meta.Consumable"`

The second option (I've tested both) would be to just have the mod list the items as:

```
{
    "Name": "Meta_Carrot_Seed",
    "Itemable": {
        "RowName": "Item_Meta_Loadout_Kit"
    },
    "Consumable": {
        "RowName": "Item_Meta_Loadout_Kit"
    }
},
```

and

```
{
    "Name": "Meta_Berry_Seed",
    "Itemable": {
        "RowName": "Item_Meta_Cabin_Kit"
    },
    "Consumable": {
        "RowName": "Item_Meta_Cabin_Kit"
    }
},
```

**Comment by DreamingLamb** [comment]
Just had a look, the above also looks like you don't need to include:

```
\data\Items\D_ItemTemplate.json
	DeleteLine("Defaults")
        "ItemOwnerLookupId": -1			' This line removed, stops tracking who owns O2 and water canteens!
```

My mod file just has:

```
{
    "CurrentFile": "Items-D_ItemTemplate.json",
    "File_Items": [{
        "Name": "........
        "ItemStaticData":......
}
```

**Comment by laanp** [comment]
Hi , thanks for the feedback, I never noticed this before, I think you are right, and just leaving the:
"TagName": "Item.Meta.Consumable" as is, would be sufficient.

Also...
the added section:
            "Focusable": {
                "RowName": "Focusable_1H"
            },
            "Actionable": {
                "RowName": "Generic_Consumable"
            },
            "CraftingExperience": 10
        },
for both the Meta_Carrot_Seed and the Meta_Berry_Seed sections, as I added this from another mod, and noticed my other kits don't use this section and work just fine.

Appreciate the comments! - I will fix for my next release
