### ISSUE TITLE
Workshop research always failing

### ISSUE THREAD

**Issue by marcelosgc** [laanp/Icarus_Mods#3]
Hello, 

Every time i try to research anything related to this mod, it gives me the error of "Fail to research on the Workshop". 
I'm using the last version of the game and the last version of the mod. 
![Captura de tela 2024-02-19 084148](https://github.com/laanp/Icarus_Mods/assets/33937158/effb3959-50d8-477b-b4f2-0966550d6903)

Thank you and have a great week!

**Comment by laanp** [comment]
I just downloaded the mod today and installed it, and cannot reproduce this error.  Can you verify you have the following file installed in your mods folder:  "laanp-Combined_QOL_v1_w115_P.pak" and that is the only file in the mods directory: "C:\Program Files (x86)\Steam\steamapps\common\Icarus\Icarus\Content\Paks\mods" - (assuming you have steam installed on C: drive)?

**Comment by marcelosgc** [comment]
Hello! 

Yep, everything is ok on the mod folder. 
But i managed to make work, it was a problem with my user folder and the workshop json. 
Thank you for the attention btw!
