### ISSUE TITLE
Pete's Ore Extractor Not Starting

### ISSUE THREAD

**Issue by marcelosgc** [laanp/Icarus_Mods#4]
Hello,

So i've updated the mods and the game and since then the Pete's Ore Extractor cant start. You click on button to start the dig process but wont turn. 

Thank you for the updates on this,

**Comment by laanp** [comment]
Thank you for reporting this.  I am aware of this problem and have fixed the issue, but was waiting for this week’s update (w119) which should be out late today/tomorrow. Cheers!
