### ISSUE TITLE
Issues with electrical power.

### ISSUE THREAD

**Issue by Klyde183** [laanp/Icarus_Mods#5]
I have noticed that the electricity is not connecting to anything when using the generator with Pete's fuel cell. I have not tried using just regular biofuel. But I have connected lights and material processor. The Processor shows idling when turned on, but when you put something in the Que the processor turns off, but to turn it back on one has to clear the Que. The lights show they require power, but are snapped correctly. I am only running this mod., and no other mods.

**Comment by Klyde183** [comment]
I have done all of what you said and still have this issue, do you have time to meet up on discord, so I can share my screen with you?

**Comment by laanp** [comment]
You bet!  My user name is "laanp" on Discord, send me a friend request, and we can link up to see what's going on.

**Comment by Klyde183** [comment]
request sent

**Comment by laanp** [comment]
Connected with Klyde and discovered some connection issues with the generator, all is working with the mod!
