### ISSUE TITLE
Fog of prometheus 

### ISSUE THREAD

**Issue by Al-Rashed** [laanp/Icarus_Mods#6]
Hi Man,

Thank you so much for your amazing mods. Without them we won't play this game. 

Please can you make something to remove prometheus fog ? The pink/purple smoke it's ugly and annoying. 

Thanks,
Your No1 Fan

**Comment by laanp** [comment]
Hi Al-Rashed,
Thank you for the comment, much appreciated!
I already have this mod created!  It’s called “laanp-NoPurpleSky”
You can get this mod and others from my GitHub page at:
https://github.com/laanp/Icarus_Mods_Separated

This is the main Readme files entry page. To get the latest mod pak files (which are updated weekly)
click on the "Latest" Release button on the right side of the page.
